version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    env_file:
      - .env.mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data:/data/db
  backend_app:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mysqldb
    env_file:
      - .env.backend
    volumes:
      - ./logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  frontend_app:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend_app
    env_file:
      - .env.frontend
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
volumes:
  data:
  logs:
