version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: sm_db
    env_file:
      - .env.mysql
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  backend_app:
    container_name: sm_be
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mysqldb
    env_file:
      - backend/.env
    volumes:
      - ./logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  frontend_app:
    container_name: sm_fe
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend_app
    env_file:
      - frontend/.env
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
volumes:
  db-data:
    name: sm_database_volume
  logs:
